import subprocess
import sys
import os

def execute_python_code(code_string):
    """Runs the code generated by the LLM and returns the stdout/stderr."""
    temp_file = "temp_training_code.py"
    with open(temp_file, "w") as f:
        f.write(code_string)
    
    if hasattr(sys, 'real_prefix') or (hasattr(sys, 'base_prefix') and sys.base_prefix != sys.prefix):
        python_cmd = sys.executable
    else:
        possible_venvs = [
            os.path.join(os.getcwd(), '.venv', 'bin', 'python'),
            os.path.join(os.getcwd(), 'venv', 'bin', 'python'),
            os.path.join(os.getcwd(), '.venv', 'Scripts', 'python.exe'),
            os.path.join(os.getcwd(), 'venv', 'Scripts', 'python.exe')
        ]
        
        python_cmd = None
        for venv_python in possible_venvs:
            if os.path.exists(venv_python):
                python_cmd = venv_python
                break
        
        if python_cmd is None:
            python_cmd = sys.executable
    
    try:
        result = subprocess.run([python_cmd, temp_file], capture_output=True, text=True, timeout=60)
        output = f"STDOUT:\n{result.stdout}\n\nSTDERR:\n{result.stderr}\n\nExit Code: {result.returncode}"
        return output
    except subprocess.TimeoutExpired:
        return "Error: Execution timed out."
    except Exception as e:
        return f"Error: {str(e)}"
